- name: Installing squid
  yum:
    name: squid
    state: present

# TODO check dest and name
- name: Copy config file
  copy:
    src: ../files/file1.conf
    dest: /etc/squid/conf/file1.conf
    owner: root
    group: root
    mode: 0644

- name: Ensure squid is started and enabled
  service:
    name: squid
    state: started
    enabled: true
